source 'https://github.com/flywithbug/CCPodspec.git'

platform:ios,'10.0'
use_frameworks!



target 'Example' do
	pod 'FBDebug', :path => '../'
  pod 'FBRouter', :path => '~/SynologyDrive/Private/FBRouter/'
end

